"""Contract tests for the flow to flow delegation object shapes.

These tests are the freeze. They assert that the shapes a delegated call
uses (the request a parent sends, the task record a child is represented
by, the artifact a child result becomes) match the document under
``docs/guide/flow-delegation-shapes.md`` and the JSON schemas shipped
beside the helper, so a later child of #621 cannot quietly invent a
second field vocabulary.

No runtime behaviour is exercised: the module under test loads JSON and
validates dictionaries.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, List

import pytest

from preloop.a2a.delegation import (
    A2A_PROTOCOL_BINDING,
    A2A_PROTOCOL_VERSION,
    A2A_SPECIFICATION_VERSION,
    DELEGATION_METADATA_KEYS,
    REFUSAL_REASONS,
    REFUSED_STATUS,
    STATUS_TO_TASK_STATE,
    DelegationShapeError,
    is_refusal,
    load_schema,
    task_state_for_status,
    validate_delegation_request,
    validate_delegation_task,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
DOC_PATH = REPO_ROOT.parent / "docs" / "guide" / "flow-delegation-shapes.md"

# One valid record of each shape, written by hand rather than generated by
# the code under test: a builder that agrees with itself proves nothing.
REQUEST_EXAMPLE: Dict[str, Any] = {
    "messageId": "1b9c2f3d4e5a6b7c8d9e0f1a2b3c4d5e",
    "contextId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
    "role": "ROLE_USER",
    "parts": [
        {"text": "Review the repository and report findings."},
        {
            "data": {"repository": "example/widget", "since": "2026-09-01"},
            "mediaType": "application/json",
        },
    ],
    "metadata": {
        "preloop.ai/kind": "delegation_request",
        "preloop.ai/parentExecutionId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
        "preloop.ai/rootExecutionId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
        "preloop.ai/flowId": "9a8b7c6d-5e4f-4031-9283-1a2b3c4d5e6f",
        "preloop.ai/flowName": "Repository review",
        "preloop.ai/depth": 1,
    },
}

TASK_EXAMPLE: Dict[str, Any] = {
    "id": "5c6d7e8f-9a0b-4c1d-8e2f-3a4b5c6d7e8f",
    "contextId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
    "status": {
        "state": "TASK_STATE_COMPLETED",
        "timestamp": "2026-09-15T10:04:11Z",
    },
    "artifacts": [
        {
            "artifactId": "5c6d7e8f-9a0b-4c1d-8e2f-3a4b5c6d7e8f/result",
            "name": "result",
            "parts": [
                {
                    "data": {"verdict": "pass", "findings": []},
                    "mediaType": "application/json",
                }
            ],
        }
    ],
    "metadata": {
        "preloop.ai/kind": "delegation_task",
        "preloop.ai/executionId": "5c6d7e8f-9a0b-4c1d-8e2f-3a4b5c6d7e8f",
        "preloop.ai/parentExecutionId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
        "preloop.ai/rootExecutionId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
        "preloop.ai/flowId": "9a8b7c6d-5e4f-4031-9283-1a2b3c4d5e6f",
        "preloop.ai/flowName": "Repository review",
        "preloop.ai/depth": 1,
        "preloop.ai/status": "SUCCEEDED",
        "preloop.ai/cost": 0.42,
        "preloop.ai/tokens": 18422,
        "preloop.ai/consoleUrl": (
            "/console/flows/executions/5c6d7e8f-9a0b-4c1d-8e2f-3a4b5c6d7e8f"
        ),
    },
}

REFUSAL_EXAMPLE: Dict[str, Any] = {
    "id": "7d8e9f0a-1b2c-4d3e-8f40-5a6b7c8d9e0f",
    "contextId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
    "status": {
        "state": "TASK_STATE_REJECTED",
        "timestamp": "2026-09-15T10:04:11Z",
    },
    "metadata": {
        "preloop.ai/kind": "delegation_task",
        "preloop.ai/parentExecutionId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
        "preloop.ai/rootExecutionId": "3f1a2b3c-4d5e-6f70-8192-a3b4c5d6e7f8",
        "preloop.ai/flowId": "9a8b7c6d-5e4f-4031-9283-1a2b3c4d5e6f",
        "preloop.ai/depth": 2,
        "preloop.ai/status": "REFUSED",
        "preloop.ai/refusalReason": "depth_exceeded",
    },
}


def _doc_text() -> str:
    return DOC_PATH.read_text(encoding="utf-8")


def _doc_examples(marker: str) -> List[Dict[str, Any]]:
    """JSON blocks the document tags with ``<!-- validates: <marker> -->``."""
    pattern = re.compile(
        r"<!--\s*validates:\s*" + re.escape(marker) + r"\s*-->\s*```json\n(.*?)```",
        re.DOTALL,
    )
    return [json.loads(block) for block in pattern.findall(_doc_text())]


class TestSchemasValidateTheExamples:
    def test_request_example_is_valid(self) -> None:
        validate_delegation_request(REQUEST_EXAMPLE)

    def test_task_example_is_valid(self) -> None:
        validate_delegation_task(TASK_EXAMPLE)

    def test_refusal_example_is_valid(self) -> None:
        validate_delegation_task(REFUSAL_EXAMPLE)

    def test_request_without_a_part_is_rejected(self) -> None:
        payload = json.loads(json.dumps(REQUEST_EXAMPLE))
        payload["parts"] = []
        with pytest.raises(DelegationShapeError):
            validate_delegation_request(payload)

    def test_request_with_agent_role_is_rejected(self) -> None:
        payload = json.loads(json.dumps(REQUEST_EXAMPLE))
        payload["role"] = "ROLE_AGENT"
        with pytest.raises(DelegationShapeError):
            validate_delegation_request(payload)

    def test_request_with_an_unknown_metadata_key_is_rejected(self) -> None:
        payload = json.loads(json.dumps(REQUEST_EXAMPLE))
        payload["metadata"]["preloop.ai/budgetCeiling"] = 5
        with pytest.raises(DelegationShapeError):
            validate_delegation_request(payload)

    def test_request_may_not_claim_a_child_execution_id(self) -> None:
        payload = json.loads(json.dumps(REQUEST_EXAMPLE))
        payload["metadata"]["preloop.ai/executionId"] = TASK_EXAMPLE["id"]
        with pytest.raises(DelegationShapeError):
            validate_delegation_request(payload)

    def test_task_without_an_execution_id_is_rejected(self) -> None:
        payload = json.loads(json.dumps(TASK_EXAMPLE))
        del payload["metadata"]["preloop.ai/executionId"]
        with pytest.raises(DelegationShapeError):
            validate_delegation_task(payload)

    def test_refusal_without_a_reason_is_rejected(self) -> None:
        payload = json.loads(json.dumps(REFUSAL_EXAMPLE))
        del payload["metadata"]["preloop.ai/refusalReason"]
        with pytest.raises(DelegationShapeError):
            validate_delegation_task(payload)

    def test_refusal_reason_is_from_the_frozen_list(self) -> None:
        payload = json.loads(json.dumps(REFUSAL_EXAMPLE))
        payload["metadata"]["preloop.ai/refusalReason"] = "because_i_said_so"
        with pytest.raises(DelegationShapeError):
            validate_delegation_task(payload)

    def test_task_with_an_unknown_state_is_rejected(self) -> None:
        payload = json.loads(json.dumps(TASK_EXAMPLE))
        payload["status"]["state"] = "completed"
        with pytest.raises(DelegationShapeError):
            validate_delegation_task(payload)


class TestStatusMapping:
    """One case per Preloop execution status, refusal included."""

    EXPECTED = {
        "PENDING": "TASK_STATE_SUBMITTED",
        "INITIALIZING": "TASK_STATE_SUBMITTED",
        "STARTING": "TASK_STATE_SUBMITTED",
        "RUNNING": "TASK_STATE_WORKING",
        "RESUMING": "TASK_STATE_WORKING",
        "WAITING_FOR_HUMAN": "TASK_STATE_INPUT_REQUIRED",
        "WAITING_FOR_CHILDREN": "TASK_STATE_WORKING",
        "SUCCEEDED": "TASK_STATE_COMPLETED",
        "FAILED": "TASK_STATE_FAILED",
        "TIMEOUT": "TASK_STATE_FAILED",
        "TIMED_OUT": "TASK_STATE_FAILED",
        "ABORTED": "TASK_STATE_FAILED",
        "STOPPED": "TASK_STATE_CANCELED",
        "CANCELLED": "TASK_STATE_CANCELED",
        "CANCELED": "TASK_STATE_CANCELED",
        "REFUSED": "TASK_STATE_REJECTED",
    }

    @pytest.mark.parametrize("status,state", sorted(EXPECTED.items()))
    def test_each_status_maps(self, status: str, state: str) -> None:
        assert task_state_for_status(status) == state

    def test_table_has_no_extra_rows(self) -> None:
        assert dict(STATUS_TO_TASK_STATE) == self.EXPECTED

    def test_refusal_is_not_a_failure(self) -> None:
        assert task_state_for_status(REFUSED_STATUS) == "TASK_STATE_REJECTED"
        assert task_state_for_status("FAILED") == "TASK_STATE_FAILED"
        assert task_state_for_status(REFUSED_STATUS) != task_state_for_status("FAILED")
        assert is_refusal(REFUSED_STATUS)
        assert not is_refusal("FAILED")

    def test_unknown_status_raises_rather_than_guessing(self) -> None:
        with pytest.raises(DelegationShapeError):
            task_state_for_status("WAITING_FOR_A_STATUS_NOBODY_ADDED")

    def test_every_mapped_state_is_an_a2a_state(self) -> None:
        a2a_states = {
            "TASK_STATE_UNSPECIFIED",
            "TASK_STATE_SUBMITTED",
            "TASK_STATE_WORKING",
            "TASK_STATE_COMPLETED",
            "TASK_STATE_FAILED",
            "TASK_STATE_CANCELED",
            "TASK_STATE_INPUT_REQUIRED",
            "TASK_STATE_REJECTED",
            "TASK_STATE_AUTH_REQUIRED",
        }
        assert set(STATUS_TO_TASK_STATE.values()) <= a2a_states


class TestDocumentAndSchemaAgree:
    def test_document_exists_and_disclaims_a2a_support(self) -> None:
        text = _doc_text().lower()
        assert "not a2a support" in text
        assert "no json-rpc endpoint" in text
        assert "no agent card" in text

    def test_document_cites_the_normative_version_and_binding(self) -> None:
        text = _doc_text()
        assert A2A_SPECIFICATION_VERSION in text
        assert f"protocol version {A2A_PROTOCOL_VERSION}" in text.lower()
        assert A2A_PROTOCOL_BINDING in text

    def test_load_schema_returns_a_copy(self) -> None:
        first = load_schema("delegation_request")
        first["poison"] = True
        second = load_schema("delegation_request")
        assert "poison" not in second

    def test_metadata_key_list_matches_the_schemas(self) -> None:
        request_keys = set(
            load_schema("delegation_request")["$defs"]["requestMetadata"]["properties"]
        )
        task_keys = set(
            load_schema("delegation_task")["$defs"]["taskMetadata"]["properties"]
        )
        assert request_keys | task_keys == set(DELEGATION_METADATA_KEYS)

    def test_metadata_key_list_matches_the_document(self) -> None:
        documented = set(re.findall(r"`(preloop\.ai/[A-Za-z]+)`", _doc_text()))
        assert documented == set(DELEGATION_METADATA_KEYS)

    def test_status_table_in_the_document_matches_the_code(self) -> None:
        rows = re.findall(
            r"^\|\s*`([A-Z_]+)`\s*\|\s*`(TASK_STATE_[A-Z_]+)`\s*\|",
            _doc_text(),
            re.MULTILINE,
        )
        assert dict(rows) == dict(STATUS_TO_TASK_STATE)

    def test_refusal_reasons_in_the_document_match_the_schema(self) -> None:
        documented = set(re.findall(r"^\|\s*`([a-z_]+)`\s*\|", _doc_text(), re.M))
        assert set(REFUSAL_REASONS) <= documented

    def test_document_examples_validate(self) -> None:
        requests = _doc_examples("delegation_request")
        tasks = _doc_examples("delegation_task")
        assert requests, "the document shows no request example"
        assert tasks, "the document shows fewer than two task examples"
        for example in requests:
            validate_delegation_request(example)
        for example in tasks:
            validate_delegation_task(example)
